### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/gator#2]
It would be nice to add some pre-commit hooks, especially formatting and linting. Here's a few suggestions:

```yaml
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-ast
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    flake8-docstrings,
                    flake8-mutable,
                    flake8-debugger,
                    pep8-naming,
                    flake8-simplify,
                    flake8-eradicate,
                ]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.2.1
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.812'
      hooks:
          - id: mypy
    - repo: https://github.com/pycqa/isort
      rev: 5.6.3
      hooks:
          - id: isort
            name: isort (python)
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
```
